
services:
  bot:
    build: .
    container_name: chat-bot-gpt
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPEN_AI_KEY=${OPEN_AI_KEY}
      - BASE_URL=${BASE_URL}
    ports:
      - "8501:8501"
